# Generated by Django 2.1.7 on 2019-02-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_type',
            field=models.PositiveIntegerField(choices=[(1, 'General Club'), (2, 'Optional Club'), (3, 'Special Club')], default=1),
            preserve_default=False,
        ),
    ]
